### ISSUE TITLE
Transformer implementation

### ISSUE THREAD

**Issue by shawntan** [google-deepmind/neural_networks_chomsky_hierarchy#1]
I'd like to refer to the attention and feedforward implementation for transformers here:
https://github.com/deepmind/neural_networks_chomsky_hierarchy/blob/main/models/transformer.py#L361-L379

I've heard that some implementations compute attention and the feedforward in parallel to speed up computation, is this the case here?

Also, the feedforward seems to be missing an initial linear transform, the `relu` is directly applied on `h`.

**Comment by anianruoss** [comment]
Hi @shawntan, thank you for your comment!

Indeed, the current code provides an implementation of the Universal Transformer ([Dehghani et al., 2019](https://arxiv.org/pdf/1807.03819.pdf)). We reran our experiments with the original Transformer ([Vaswani et al., 2017](https://arxiv.org/pdf/1706.03762.pdf)) and did not find a significant difference in the results. We will update the results and the code with the next revision of our paper.

**Comment by shawntan** [comment]
I have implemented a vanilla transformer and have found the same results.

I'm curious how the current implementation implements a universal transformer though.
https://github.com/deepmind/neural_networks_chomsky_hierarchy/blob/main/models/transformer.py#L362-L379
Aren't the parameters being initialised within the for-loop, therefore having unique parameters at every layer?
