### ISSUE TITLE
Version alignment under conda for ubuntu22.04.2.LTS & nvidia-driver-530

### ISSUE THREAD

**Issue by jabowery** [google-deepmind/neural_networks_chomsky_hierarchy#3]
The attached file contains exports of a version-aligned conda environment that, under ubuntu22.04.2.LTS and nvidia-driver-530 properly executes:

`$ python training/example.py`

It may also be necessary, on some systems, to execute:
`conda install -c nvidia cuda-nvcc`

The exports were created by these commands as recommended for differing degrees of specificity:

![image](https://user-images.githubusercontent.com/57646/222981309-cd2ebc96-16cf-434f-a5b3-f52f890104d5.png)

[ubuntu22.04.2.LTS-nvidia-driver-530-conda-ENVs.tar.gz](https://github.com/deepmind/neural_networks_chomsky_hierarchy/files/10892733/ubuntu22.04.2.LTS-nvidia-driver-530-conda-ENVs.tar.gz)

**Comment by anianruoss** [comment]
Great, thanks!
