### ISSUE TITLE
Bug in the Solve Equation task?

### ISSUE THREAD

**Issue by FlorianDietz** [google-deepmind/neural_networks_chomsky_hierarchy#8]
Based on the paper, I think Solve Equation may not be implemented correctly.
In the example you give, -(z-2)*(4-3*(-2))=0 does not have a unique solution. In fact, all values of z are a valid solution since (4-3*(-2))%5=0. This makes me suspect that the task does not train what you think it trains. The input/target pairs on which the model is trained only accept a single solution, even if other values would also be valid. The neural network is therefore trained not just to solve the equation, but to reverse-engineer the data generation process you used in order to make sure that it submits the expected answer when several values would be correct.

Solve Equation has lower accuracies than other DCF tasks. It might be worth investigating if that is caused by the issue I described. If so, it could strengthen the point you make in your paper, and the table would no longer be conspicuously missing a bold item that I would visually expect to be there.

**Comment by fazega** [comment]
In the paper we did not use the multiplication for solve_equation as that could lead to equations with multiple solutions, as you correctly pointed out. We forgot to update the description of this task, but all the results are correct.
I updated the code in commit [ed7e055](https://github.com/google-deepmind/neural_networks_chomsky_hierarchy/commit/ed7e055478a122c5baed7960e0d99b8c5e05283f), removing the mult option completely.
